"""Transliterate Dendro-GR's BSSN constraint CSE (Hamiltonian + momentum) → JAX.

Source: vendored ``physcon.cpp`` — Dendro's ``physical_constraints`` routine. Its
single CSE block emits ``psi4_real/img``, ``ham`` and ``mom0/1/2`` over the fields,
the constraint derivative inputs (``grad_i_f[pp]`` / ``grad2_i_j_f[pp]``), and the
coordinates ``x,y,z`` (used only by the psi4 Newman-Penrose tetrad).

We want only ``ham`` + ``mom0/1/2`` (psi4 is a Phase-6 extraction tool), so this
transliterator does **dead-code elimination**: starting from those four outputs it
keeps only the reachable SSA statements. That drops the entire psi4 subtree — and
with it the ``x/y/z`` coordinate dependence and the ``sqrt`` calls — leaving a clean
constraints algebra over fields + derivatives only (``pow`` the lone function, like
the RHS). The reduced module is committed and reviewable.

Run:  ``python -m bssn3d._codegen_constraints``
"""

import hashlib
import re
from datetime import date
from pathlib import Path

from ._codegen import _strip_comments, _LAMBDA_RE, _GRAD1_RE, _GRAD2_RE, FIELD_INPUTS

PHYSCON = Path(__file__).resolve().parent / "vendor" / "physcon.cpp"
OUT_PATH = Path(__file__).resolve().parent / "_constraints_generated.py"

# Dendro output token -> our constraint name. psi4 deliberately excluded.
TARGET = {"ham": "H", "mom0": "M0", "mom1": "M1", "mom2": "M2"}

_IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
_NOT_NAMES = {"pow", "sqrt", "jnp"}


def _extract_block(text: str) -> str:
    """The ``// Dendro: {{{ ... }}}`` CSE block that contains ``ham[pp]``."""
    lines = text.splitlines()
    h = next(i for i, l in enumerate(lines) if l.strip().startswith("ham[pp]"))
    start = max(i for i in range(h) if "Dendro: {{{" in lines[i])
    end = next(i for i in range(h, len(lines)) if "Dendro: }}}" in lines[i])
    return "\n".join(lines[start:end + 1])


def _translate(expr: str) -> str:
    expr = _LAMBDA_RE.sub("lmbda", expr)          # (no lambdas in constraints)
    expr = re.sub(r"\bsqrt\(", "jnp.sqrt(", expr)  # only psi4 uses it; DCE'd away
    return expr


def _statements(block: str):
    """(lhs, rhs) for each ``[double] X = …;`` line, in order."""
    code = _strip_comments(block)
    for raw in code.split(";"):
        s = raw.strip()
        if not s:
            continue
        s = s.replace("[pp]", "")
        for pre in ("const double ", "double "):
            if s.startswith(pre):
                s = s[len(pre):]
                break
        lhs, rhs = s.split("=", 1)
        yield lhs.strip(), _translate(rhs.strip())


def parse(src: Path = PHYSCON):
    stmts = list(_statements(_extract_block(src.read_text())))
    defs = {lhs: rhs for lhs, rhs in stmts}

    # reachability (DCE) from the four constraint outputs
    needed = set()
    stack = list(TARGET)
    while stack:
        t = stack.pop()
        if t in needed:
            continue
        needed.add(t)
        if t in defs:
            for tok in _IDENT.findall(defs[t]):
                if tok not in _NOT_NAMES and tok not in needed:
                    stack.append(tok)

    kept = [(lhs, rhs) for lhs, rhs in stmts if lhs in needed]
    inputs = sorted(n for n in needed if n not in defs)

    grad1 = sorted({(int(a), f) for n in inputs for a, f in _GRAD1_RE.findall(n)})
    grad2 = sorted({(int(i), int(j), f) for n in inputs
                    for i, j, f in _GRAD2_RE.findall(n)})
    grad_names = {f"grad_{a}_{f}" for a, f in grad1} | \
                 {f"grad2_{i}_{j}_{f}" for i, j, f in grad2}
    fields = [n for n in inputs if n in FIELD_INPUTS]
    other = [n for n in inputs if n not in FIELD_INPUTS and n not in grad_names]
    return kept, fields, grad1, grad2, other


def generate(src: Path = PHYSCON, out: Path = OUT_PATH) -> Path:
    kept, fields, grad1, grad2, other = parse(src)
    if other:
        # x/y/z would land here if ham/mom depended on coordinates (they must not)
        raise RuntimeError(f"unexpected non-field/grad inputs after DCE: {other}")

    src_hash = hashlib.sha256(src.read_bytes()).hexdigest()[:16]
    grad1_names = [f"grad_{a}_{f}" for a, f in grad1]
    grad2_names = [f"grad2_{i}_{j}_{f}" for i, j, f in grad2]

    L, w = [], None
    out_lines = L.append

    out_lines('"""AUTO-GENERATED by bssn3d._codegen_constraints — DO NOT EDIT BY HAND.')
    out_lines("")
    out_lines(f"Hamiltonian + momentum constraints transliterated from Dendro-GR {src.name}")
    out_lines(f"  sha256[:16] = {src_hash}")
    out_lines(f"  generated   = {date.today().isoformat()}")
    out_lines(f"  statements  = {len(kept)} (after DCE from ham/mom0-2; psi4 dropped)")
    out_lines(f"  grad1 = {len(grad1)}   grad2 = {len(grad2)}")
    out_lines("")
    out_lines("Regenerate:  python -m bssn3d._codegen_constraints")
    out_lines('"""')
    out_lines("import jax.numpy as jnp")
    out_lines("")
    out_lines(f"FIELD_INPUTS = {fields!r}")
    out_lines(f"GRAD1_INPUTS = {[list(g) for g in grad1]!r}")
    out_lines(f"GRAD2_INPUTS = {[list(g) for g in grad2]!r}")
    out_lines(f"OUTPUTS = {list(TARGET.values())!r}")
    out_lines("")
    out_lines("")
    out_lines("def constraints_algebra(F, D):")
    out_lines('    """Hamiltonian + momentum constraints (derivatives as inputs).')
    out_lines("")
    out_lines("    F: dict field-name -> array;  D: dict deriv-name -> array.")
    out_lines("    Returns {'H', 'M0', 'M1', 'M2'} -> array.")
    out_lines('    """')
    for name in fields:
        out_lines(f'    {name} = F["{name}"]')
    for name in grad1_names + grad2_names:
        out_lines(f'    {name} = D["{name}"]')
    out_lines("")
    for lhs, rhs in kept:
        out_lines(f"    {lhs} = {rhs}")
    out_lines("")
    out_lines("    return {")
    for tok, cname in TARGET.items():
        out_lines(f'        "{cname}": {tok},')
    out_lines("    }")

    out.write_text("\n".join(L) + "\n")
    return out


if __name__ == "__main__":
    p = generate()
    print(f">> wrote {p}")
