"""Step 3.2d Increment 2 — emit the **fused tiled** BSSN Pallas kernel (shift-stencil).

One ``pallas_call`` over power-of-2 output tiles. Per tile, per field:
  * read shifted ``BS**3`` windows from the SINGLE padded grid via ``pl.ds`` (the L2-served
    load proven to lower on H200) and weighted-sum them into the field's derivatives —
    the **shift-stencil**: no HP window, **no 4D broadcast transient**. (The earlier
    broadcast-multiply-reduce form compiled ~quadratically in deriv count — 24 derivs =
    256 s on H200 → 138 ≈ 2 h — because each deriv materialized an 8×16×16×16 transient.
    The shift form keeps every value at BS**3, so ptxas register pressure stays flat.)
  * the field's interior value is the centred (zero-offset) load.
Then cast the 24 fields + 138 derivatives to fp32 and run the 3.2b scheduled algebra → the
24 RHS. The 138 derivative arrays never touch HBM; the field grid is ONE HBM copy.

Math identical to ``derivative_bundle`` up to fp summation order (round-off): a first
derivative is ``Σ_m c1[m] f(x+(m-NG)e_a)/d_a``; a diagonal second ``Σ_m c2[m] f/d_i²``; a
mixed second the ``(2NG+1)²`` outer product ``Σ c1[mi]c1[mj] f /(d_i d_j)``. FD order via
``BSSN_FD_ORDER`` (coeffs from ``SpatialDerivative(ORDER)``; tap structure is order-agnostic).

CPU ``interpret`` validates the MATH (== verbatim on the interior); the compile/spill/regime
is the H200 push. ``BSSN_TILE_NDERIV`` caps the deriv count for a fast smoke-test.

Run:  ``python -m bssn3d.fused_tiled_backend``  (regenerates ``_bssn_rhs_fused_tiled.py``).
"""

from __future__ import annotations

import hashlib
from datetime import date
from pathlib import Path

from ._codegen import DENDRO_CSE, FIELD_INPUTS, RHS_TO_FIELD
from ._bssn_rhs_generated import GRAD1_INPUTS, GRAD2_INPUTS
from .staging import build_dag, select_schedule, schedule_pylines
from .pallas_backend import DEFAULT_BUDGET, SCAL_SINGLE

FUSED_TILED_OUT = Path(__file__).resolve().parent / "_bssn_rhs_fused_tiled.py"

GRAD1_NAMES = [f"grad_{a}_{f}" for a, f in GRAD1_INPUTS]
GRAD2_NAMES = [f"grad2_{i}_{j}_{f}" for i, j, f in GRAD2_INPUTS]
DERIV_NAMES = GRAD1_NAMES + GRAD2_NAMES
INPUT_NAMES = FIELD_INPUTS + DERIV_NAMES
OUTPUT_TOKENS = list(RHS_TO_FIELD)
OUTPUT_FIELDS = [RHS_TO_FIELD[t] for t in OUTPUT_TOKENS]


def _shift_spec() -> dict:
    """name -> (fidx, kind, axes); order-INDEPENDENT (only the tap count/offsets, computed
    in the kernel from runtime NG, depend on order). kind: 'g1' first, 'g2d' diagonal
    second, 'g2m' mixed second."""
    fidx = {f: i for i, f in enumerate(FIELD_INPUTS)}
    spec = {}
    for a, f in GRAD1_INPUTS:
        spec[f"grad_{a}_{f}"] = (fidx[f], "g1", (a,))
    for i, j, f in GRAD2_INPUTS:
        if i == j:
            spec[f"grad2_{i}_{j}_{f}"] = (fidx[f], "g2d", (i,))
        else:
            spec[f"grad2_{i}_{j}_{f}"] = (fidx[f], "g2m", (i, j))
    return spec


def _deriv_block_lines(nlim_expr: str) -> list[str]:
    """Field-streamed shift-stencil derivative + interior-value assignments, in
    FIELD_INPUTS order. The field value is the centred load; each derivative is a
    `_deriv_shift` call (the order-dependent tap sum lives in the emitted helper). Honors
    the runtime NDERIV cap by falling back to the field value (a capped kernel is a
    smoke-test, not a correct RHS)."""
    grads_by_field: dict[str, list[str]] = {}
    spec = _shift_spec()
    for name in DERIV_NAMES:
        grads_by_field.setdefault(FIELD_INPUTS[spec[name][0]], []).append(name)

    lines = ["# --- on-chip shift-stencil derivatives (field-streamed; BS**3 pl.ds loads, "
             "no transient, never to HBM) ---"]
    deriv_index = {name: k for k, name in enumerate(DERIV_NAMES)}
    for fidx, f in enumerate(FIELD_INPUTS):
        # interior value = centred (zero-offset) load
        lines.append(f"{f} = _ld(grid_ref, {fidx}, _b0, _b1, _b2, 0, 0, 0)")
        for name in grads_by_field.get(f, []):
            _, kind, axes = spec[name]
            lines.append(
                f"{name} = _deriv_shift(grid_ref, {fidx}, {kind!r}, {axes!r}, "
                f"_b0, _b1, _b2, _invd) if {deriv_index[name]} < {nlim_expr} else {f}")
    return lines


def generate_fused_tiled(budget: int = DEFAULT_BUDGET, order: int = 6,
                         out: Path = FUSED_TILED_OUT) -> Path:
    dag = build_dag()
    sched = select_schedule(dag, budget=budget)
    algebra = schedule_pylines(dag, sched.materialize)
    src_hash = hashlib.sha256(DENDRO_CSE.read_bytes()).hexdigest()[:16]
    NG = order // 2

    L: list[str] = []
    w = L.append
    w('"""AUTO-GENERATED by bssn3d.fused_tiled_backend — DO NOT EDIT BY HAND.')
    w("")
    w("Fused TILED BSSN Pallas kernel (Step 3.2d Increment 2, shift-stencil). One")
    w("pallas_call over power-of-2 output tiles: per field, shifted BS**3 pl.ds loads from")
    w("the SINGLE padded grid (L2-served, no 4D transient) → weighted-summed derivatives,")
    w("then the fp32 scheduled algebra → 24 RHS. The 138 derivative arrays never touch HBM.")
    w("CPU interpret validates MATH (== verbatim on the interior); compile/spill/regime is")
    w("the H200 push.")
    w("")
    w(f"Transliterated from Dendro-GR  {DENDRO_CSE.name}  sha256[:16] = {src_hash}")
    w(f"  generated = {date.today().isoformat()}  |  FD order = {order} (NG={NG})  |  "
      f"budget = {budget} regs")
    w(f"  materialized = {len(sched.materialize)}   peak_live = {sched.peak_live}   "
      f"recompute = {sched.multiplier:.2f}x")
    w("")
    w("Regenerate:  python -m bssn3d.fused_tiled_backend")
    w('"""')
    w("")
    w("import os")
    w("import jax")
    w("import jax.numpy as jnp")
    w("import numpy as np")
    w("from jax.experimental import pallas as pl")
    w("from jax.experimental.pallas import triton as plgpu")
    w("")
    w("from mcs_common.derivatives import SpatialDerivative")
    w("")
    w("# Force the Triton backend (Mosaic GPU isn't installed). Override w/ JAX_PALLAS_USE_MOSAIC_GPU=1.")
    w('if not os.environ.get("JAX_PALLAS_USE_MOSAIC_GPU"):')
    w('    jax.config.update("jax_pallas_use_mosaic_gpu", False)')
    w("")
    w(f"FIELD_INPUTS = {FIELD_INPUTS!r}")
    w(f"OUTPUT_FIELDS = {OUTPUT_FIELDS!r}")
    w(f"NF = {len(FIELD_INPUTS)}")
    w(f"NOUT = {len(OUTPUT_TOKENS)}")
    w(f"NDERIV = {len(DERIV_NAMES)}")
    w(f"ORDER = int(os.environ.get('BSSN_FD_ORDER', '{order}'))")
    w("NG = ORDER // 2")
    w('BS = int(os.environ.get("BSSN_TILE_BS", "8"))      # interior tile side (pow2)')
    w("# Runtime cap on emitted derivatives (fast lowering smoke-test). Default = all.")
    w('_NLIM = int(os.environ.get("BSSN_TILE_NDERIV", str(NDERIV)))')
    w("# Derivatives in fp64 (cancellation-accurate); algebra in fp32 (register-resident).")
    w("_FDTYPE = jnp.float64")
    w('PDTYPE = jnp.float32 if os.environ.get("BSSN_PALLAS_FP32") else jnp.float64')
    w('_NW = os.environ.get("BSSN_PALLAS_WARPS")')
    w("NUM_WARPS = int(_NW) if _NW else None")
    w('_INTERPRET = jax.default_backend() == "cpu"')
    w("")
    w("# Centred FD coefficients for the runtime ORDER, as plain tuples (a pallas kernel")
    w("# may not capture jax arrays from its closure).")
    w("_diff = SpatialDerivative(order=ORDER)")
    w("_C1 = tuple(float(x) for x in np.asarray(_diff.C1))      # length 2*NG+1")
    w("_C2 = tuple(float(x) for x in np.asarray(_diff.C2))")
    w("")
    w("")
    w("def _ld(grid_ref, fidx, b0, b1, b2, o0, o1, o2):")
    w('    """One BS**3 window from the single grid, shifted by (o0,o1,o2) from the tile')
    w("    base — the proven pl.ds ref-load (overlapping reads served by L2).\"\"\"")
    w("    return grid_ref[fidx, pl.ds(b0 + o0, BS), pl.ds(b1 + o1, BS), pl.ds(b2 + o2, BS)]")
    w("")
    w("")
    w("def _deriv_shift(grid_ref, fidx, kind, axes, b0, b1, b2, invd):")
    w('    """Shift-stencil derivative of one field: weighted sum of 2*NG+1 (or its square,')
    w("    for a mixed second) shifted BS**3 loads. No transient — every value is BS**3.\"\"\"")
    w("    if kind == 'g1':")
    w("        a = axes[0]; acc = None")
    w("        for m in range(2 * NG + 1):")
    w("            o = [0, 0, 0]; o[a] = m - NG")
    w("            t = _C1[m] * _ld(grid_ref, fidx, b0, b1, b2, o[0], o[1], o[2])")
    w("            acc = t if acc is None else acc + t")
    w("        return invd[a] * acc")
    w("    if kind == 'g2d':")
    w("        i = axes[0]; acc = None")
    w("        for m in range(2 * NG + 1):")
    w("            o = [0, 0, 0]; o[i] = m - NG")
    w("            t = _C2[m] * _ld(grid_ref, fidx, b0, b1, b2, o[0], o[1], o[2])")
    w("            acc = t if acc is None else acc + t")
    w("        return invd[i] * invd[i] * acc")
    w("    i, j = axes; acc = None                              # mixed second (outer product)")
    w("    for mi in range(2 * NG + 1):")
    w("        for mj in range(2 * NG + 1):")
    w("            o = [0, 0, 0]; o[i] = mi - NG; o[j] = mj - NG")
    w("            t = _C1[mi] * _C1[mj] * _ld(grid_ref, fidx, b0, b1, b2, o[0], o[1], o[2])")
    w("            acc = t if acc is None else acc + t")
    w("    return invd[i] * invd[j] * acc")
    w("")
    w("")
    w("def _kernel(grid_ref, invd_ref, scal_ref, out_ref):")
    w("    # grid_ref: WHOLE padded grid (NF,*pad) as memory_space=ANY; one BS**3 tile/program.")
    w("    # Tile base = NG (grid ghosts == NG since order matches grid) + tile_index*BS.")
    w("    _b0 = NG + pl.program_id(0) * BS")
    w("    _b1 = NG + pl.program_id(1) * BS")
    w("    _b2 = NG + pl.program_id(2) * BS")
    w("    _invd = (invd_ref[0], invd_ref[1], invd_ref[2])")
    # scalars
    for k, name in enumerate(SCAL_SINGLE):
        w(f"    {name} = scal_ref[{k}]")
    base = len(SCAL_SINGLE)
    w(f"    lmbda = [scal_ref[{base}], scal_ref[{base+1}], "
      f"scal_ref[{base+2}], scal_ref[{base+3}]]")
    w(f"    lambda_f = [scal_ref[{base+4}], scal_ref[{base+5}]]")
    w("")
    for ln in _deriv_block_lines("_NLIM"):
        w(f"    {ln}")
    w("")
    w("    # --- cast fields + derivatives to the algebra precision ---")
    for name in INPUT_NAMES:
        w(f"    {name} = {name}.astype(PDTYPE)")
    w("")
    w("    # --- scheduled pointwise algebra (M-temps stored, R-temps inlined) ---")
    for ln in algebra:
        w(f"    {ln}")
    w("")
    for i, tok in enumerate(OUTPUT_TOKENS):
        w(f"    out_ref[{i}] = {tok}")
    w("")
    w("")
    w("def bssn_rhs_fused_tiled(F, dx, dy, dz, eta, lmbda, lambda_f, "
      "BSSN_CAHD_C, dt, h_ssl, sig_ssl, t):")
    w('    """Fused tiled BSSN RHS (shift-stencil): fields in (dict, full padded shape),')
    w("    {field: d/dt} out (full padded shape; INTERIOR computed by the kernel, ghosts 0 —")
    w('    evolve re-syncs them). Derivatives on-chip → no derivative_bundle / D arg."""')
    w("    dx_i = dx")
    w("    shape = F['alpha'].shape                       # (Sx, Sy, Sz) incl. ng ghosts")
    w("    ng = NG")
    w("    N = tuple(s - 2 * ng for s in shape)")
    w("    assert all(n % BS == 0 for n in N), f'interior {N} not divisible by BS={BS}'")
    w("    nt = [n // BS for n in N]")
    w("    data = jnp.stack([F[n] for n in FIELD_INPUTS]).astype(_FDTYPE)")
    w("    invd = jnp.asarray([1.0 / dx, 1.0 / dy, 1.0 / dz], dtype=_FDTYPE)")
    w("    scal = jnp.asarray([eta, BSSN_CAHD_C, dt, dx_i, h_ssl, sig_ssl, t,")
    w("                        lmbda[0], lmbda[1], lmbda[2], lmbda[3],")
    w("                        lambda_f[0], lambda_f[1]], dtype=PDTYPE)")
    w("    cparams = (plgpu.CompilerParams(num_warps=NUM_WARPS)")
    w("               if NUM_WARPS is not None else None)")
    w("    out = pl.pallas_call(")
    w("        _kernel,")
    w("        grid=(nt[0], nt[1], nt[2]),")
    w("        in_specs=[pl.BlockSpec(memory_space=pl.ANY),            # single grid (HBM)")
    w("                  pl.BlockSpec((3,), lambda i, j, k: (0,)),")
    w("                  pl.BlockSpec((len(scal),), lambda i, j, k: (0,))],")
    w("        out_specs=pl.BlockSpec((NOUT, BS, BS, BS), lambda i, j, k: (0, i, j, k)),")
    w("        out_shape=jax.ShapeDtypeStruct((NOUT, N[0], N[1], N[2]), PDTYPE),")
    w("        interpret=_INTERPRET,")
    w("        compiler_params=cparams,")
    w("    )(data, invd, scal)")
    w("    interior = (slice(ng, ng + N[0]), slice(ng, ng + N[1]), slice(ng, ng + N[2]))")
    w("    res = {}")
    w("    for i, field in enumerate(OUTPUT_FIELDS):")
    w("        full = jnp.zeros(shape, dtype=jnp.float64)")
    w("        full = full.at[interior].set(out[i].astype(jnp.float64))")
    w("        res[field] = full")
    w("    return res")

    out.write_text("\n".join(L) + "\n")
    return out


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="Emit the fused tiled (shift-stencil) BSSN kernel.")
    ap.add_argument("--budget", type=int, default=DEFAULT_BUDGET)
    ap.add_argument("--order", type=int, default=6)
    a = ap.parse_args()
    p = generate_fused_tiled(budget=a.budget, order=a.order)
    print(f">> wrote {p}  | budget={a.budget}, FD order={a.order}")
