"""Phase 3.2d — emit the **fp64 + SMEM-trunk** derivative-fused BSSN Pallas kernel.

This is the additive fp64 sibling of ``fused_backend.py``. It is kept SEPARATE so the
fp32/BS=32 fused kernel (and its H200 gate) is untouched — this variant is for the
no-fp32 path (fp32 declined on Ricci-cancellation grounds; see ``docs/algebra.md``).

Two differences from ``fused_backend.generate_fused``:
  1. **fp64-locked** — ``PDTYPE`` is ``float64``, no ``BSSN_PALLAS_FP32`` toggle. The
     declared variant precision; the kernel never silently runs fp32.
  2. **output-fanout trunk schedule** (``staging.select_trunk_schedule``) — materialize
     the 128 temps feeding >=12 of the 24 outputs (the shared first-order tensor trunk,
     the measured spill floor), recompute the bulk (~7x). This is the correct
     materialize set for fp64 + SMEM (``[[bssn-register-pressure-structural]]``), where
     ``fused_backend``'s ``select_schedule`` budget was tuned for fp32 registers.

INCREMENT STATUS (2026-06-12):
  * **Increment 1 (this file): whole-grid, math-validated.** Reuses the proven
    whole-grid structure of ``fused_backend``; CPU interpret mode bit-matches the
    verbatim RHS. On GPU it would SPILL (128 fp64 trunk temps as kernel locals ~= 246
    regs) — that is expected and is what Increment 2 fixes. The purpose here is to lock
    the fp64 trunk schedule + fused derivatives as a correct foundation.
  * **Increment 2 (TODO, H200-gated): BS=8 halo-tiling + trunk -> SMEM scratch.** The
    per-point working set (138 derivs + 128 trunk = 266 fp64 = 532 regs) cannot be
    registers; it MUST live in SMEM. That needs a tiled grid with a halo-padded input
    BlockSpec (the 2.5D-SMEM derivative stage) and a ``scratch_shapes`` SMEM buffer for
    the materialized trunk. Budget: fits at BS<=8 (~151 KB, 1 block/SM); BS>=12 blows
    228 KB (``docs/algebra.md`` 6b). The halo crop is the Triton-0.9.2 work
    (``OZAKI_GPU_NOTES.md`` 3); not blind-written — done with the H200 in the loop.

Run:  ``python -m bssn3d.fused_fp64_backend``  (regenerates ``_bssn_rhs_fused_fp64.py``).
"""

from __future__ import annotations

import hashlib
from datetime import date
from pathlib import Path

from ._codegen import DENDRO_CSE, FIELD_INPUTS
from .staging import build_dag, select_trunk_schedule, schedule_pylines
from .fused_backend import (
    _deriv_lines, _stencil_tables, SCAL_SINGLE, OUTPUT_TOKENS, OUTPUT_FIELDS,
)

FUSED_FP64_OUT = Path(__file__).resolve().parent / "_bssn_rhs_fused_fp64.py"

# The output-fanout threshold that isolates the trunk (>=12 -> 128 temps, ~123 peak
# live, ~7x recompute). Override at generation with --min-outfanout.
DEFAULT_MIN_OUTFANOUT = 12


def generate_fused_fp64(min_outfanout: int = DEFAULT_MIN_OUTFANOUT, order: int = 8,
                        out: Path = FUSED_FP64_OUT) -> Path:
    dag = build_dag()
    sched = select_trunk_schedule(dag, min_outfanout=min_outfanout)
    algebra = schedule_pylines(dag, sched.materialize)   # trunk stored / bulk inlined
    derivs = _deriv_lines()
    c1_tbl, c2_tbl = _stencil_tables()
    src_hash = hashlib.sha256(DENDRO_CSE.read_bytes()).hexdigest()[:16]

    L: list[str] = []
    w = L.append
    w('"""AUTO-GENERATED by bssn3d.fused_fp64_backend — DO NOT EDIT BY HAND.')
    w("")
    w("fp64 + SMEM-trunk derivative-fused BSSN Pallas kernel (Step 3.2d, no-fp32 path).")
    w("Whole-grid Increment 1: fused on-chip derivatives + output-fanout trunk schedule")
    w("(materialize temps feeding the most outputs, recompute the bulk). CPU interpret")
    w("validates the MATH (== verbatim to round-off). GPU register/SMEM realization")
    w("(BS=8 halo-tiling + trunk -> SMEM scratch) is Increment 2, H200-gated.")
    w("")
    w(f"Transliterated from Dendro-GR  {DENDRO_CSE.name}  sha256[:16] = {src_hash}")
    w(f"  generated = {date.today().isoformat()}  |  FD order = {order}  |  "
      f"min_outfanout = {min_outfanout}")
    w(f"  materialized(trunk) = {len(sched.materialize)}   peak_live = {sched.peak_live}"
      f"   recompute = {sched.multiplier:.2f}x")
    w("")
    w("Regenerate:  python -m bssn3d.fused_fp64_backend")
    w('"""')
    w("")
    w("import os")
    w("import jax")
    w("import jax.numpy as jnp")
    w("from jax import lax")
    w("from jax.experimental import pallas as pl")
    w("")
    w('if not os.environ.get("JAX_PALLAS_USE_MOSAIC_GPU"):')
    w('    jax.config.update("jax_pallas_use_mosaic_gpu", False)')
    w("")
    w(f"FIELD_INPUTS = {FIELD_INPUTS!r}")
    w(f"OUTPUT_FIELDS = {OUTPUT_FIELDS!r}")
    w(f"ORDER = int(os.environ.get('BSSN_FD_ORDER', '{order}'))")
    w("# Centred FD coefficients, copied from the shared SpatialDerivative (plain")
    w("# floats: a pallas_call kernel may not capture jax arrays from its closure).")
    w(f"_C1_TBL = {c1_tbl!r}")
    w(f"_C2_TBL = {c2_tbl!r}")
    w("_C1 = _C1_TBL[ORDER]")
    w("_C2 = _C2_TBL[ORDER]")
    w("_NG = ORDER // 2")
    w("# fp64-LOCKED: this variant is the no-fp32 path (see fused_fp64_backend docstring).")
    w("PDTYPE = jnp.float64")
    w('_INTERPRET = jax.default_backend() == "cpu"')
    w(f"NF = {len(FIELD_INPUTS)}")
    w(f"NOUT = {len(OUTPUT_TOKENS)}")
    w(f"NSCAL = {len(SCAL_SINGLE) + 6}")
    w("")
    w("")
    w("def _stencil(field, coeffs, factor, axis):")
    w("    # Static pad+slice centred difference — bit-identical to SpatialDerivative.")
    w("    # jnp.pad/slice does NOT lower under Triton; the BS=8 SMEM-halo rewrite is")
    w("    # Increment 2 (H200). Interpret mode evaluates it directly.")
    w("    pad = [(_NG, _NG) if i == axis else (0, 0) for i in range(field.ndim)]")
    w("    p = jnp.pad(field, pad, mode='edge')")
    w("    n = field.shape[axis]")
    w("    return sum((coeffs[k] * factor) * lax.slice_in_dim(p, k, k + n, axis=axis)")
    w("               for k in range(len(coeffs)))")
    w("")
    w("")
    w("def _d1(field, dx, axis):")
    w("    return _stencil(field, _C1, 1.0 / dx, axis)")
    w("")
    w("")
    w("def _d2(field, dx, axis):")
    w("    return _stencil(field, _C2, 1.0 / (dx ** 2), axis)")
    w("")
    w("")
    w("def _kernel(feat_ref, scal_ref, out_ref):")
    w("    # Whole-grid program: feat_ref (NF, *shape) fields, out_ref (NOUT, *shape).")
    for k, name in enumerate(FIELD_INPUTS):
        w(f"    {name} = feat_ref[{k}]")
    for k, name in enumerate(SCAL_SINGLE):
        w(f"    {name} = scal_ref[{k}]")
    w("    dx_i = dx")                            # CAHD dx^2/dt factor uses x-spacing
    base = len(SCAL_SINGLE)
    w(f"    lmbda = [scal_ref[{base}], scal_ref[{base+1}], "
      f"scal_ref[{base+2}], scal_ref[{base+3}]]")
    w(f"    lambda_f = [scal_ref[{base+4}], scal_ref[{base+5}]]")
    w("")
    w("    # --- on-chip derivatives (field-streamed; never materialized to HBM) ---")
    for ln in derivs:
        w(f"    {ln}")
    w("")
    w("    # --- scheduled algebra (output-fanout trunk stored, bulk recomputed) ---")
    for ln in algebra:
        w(f"    {ln}")
    w("")
    for i, tok in enumerate(OUTPUT_TOKENS):
        w(f"    out_ref[{i}] = {tok}")
    w("")
    w("")
    w("def bssn_rhs_fused_fp64(F, dx, dy, dz, eta, lmbda, lambda_f, "
      "BSSN_CAHD_C, dt, h_ssl, sig_ssl, t):")
    w('    """fp64 fused BSSN RHS: fields in (dict, full padded shape), {field: d/dt} out.')
    w("")
    w("    Signature-compatible with bssn_rhs_fused; fp64-locked, output-fanout trunk")
    w('    schedule. Derivatives computed inside the kernel (no derivative_bundle)."""')
    w("    shape = F['alpha'].shape")
    w("    feat = jnp.stack([F[n] for n in FIELD_INPUTS]).astype(PDTYPE)")
    w("    scal = jnp.asarray([eta, BSSN_CAHD_C, dt, h_ssl, sig_ssl, t, dx, dy, dz,")
    w("                        lmbda[0], lmbda[1], lmbda[2], lmbda[3],")
    w("                        lambda_f[0], lambda_f[1]], dtype=PDTYPE)")
    w("    out = pl.pallas_call(")
    w("        _kernel,")
    w("        grid=(1,),")
    w("        in_specs=[pl.BlockSpec((NF,) + shape, lambda i: (0,) + (0,) * len(shape)),")
    w("                  pl.BlockSpec((NSCAL,), lambda i: (0,))],")
    w("        out_specs=pl.BlockSpec((NOUT,) + shape, lambda i: (0,) + (0,) * len(shape)),")
    w("        out_shape=jax.ShapeDtypeStruct((NOUT,) + shape, PDTYPE),")
    w("        interpret=_INTERPRET,")
    w("    )(feat, scal)")
    w("    return {field: out[i].astype(jnp.float64)")
    w("            for i, field in enumerate(OUTPUT_FIELDS)}")

    out.write_text("\n".join(L) + "\n")
    return out


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(
        description="Emit the fp64 + SMEM-trunk derivative-fused BSSN Pallas kernel.")
    ap.add_argument("--min-outfanout", type=int, default=DEFAULT_MIN_OUTFANOUT)
    ap.add_argument("--order", type=int, default=8)
    a = ap.parse_args()
    p = generate_fused_fp64(min_outfanout=a.min_outfanout, order=a.order)
    print(f">> wrote {p}  | min_outfanout={a.min_outfanout}, FD order={a.order}")
