"""Phase 3.2 / 1.2 — emit the **derivative-fused** BSSN Pallas kernel.

The algebra-only kernel (3.2c, ``pallas_backend.py``) takes the 138 derivatives as
inputs, so XLA must materialise them to HBM first (~1100 B/pt) — "wall 2", the
remaining bottleneck once fp32 collapses the algebra spill. This kernel fuses the
derivative stage **into the same ``pallas_call``**: it loads the 24 fields, computes
all ``grad_i_f`` / ``grad2_i_j_f`` on-chip with the shared Phase-1 FD stencils, and
feeds them straight into the (scheduled) algebra. The 138 derivative arrays are never
written to HBM → the read disappears.

The derivative section is emitted **field-streamed** (each field's first/second
derivatives computed together, in ``FIELD_INPUTS`` order) to mirror the production
2.5D-SMEM design (stream one field's halo through SMEM at a time). On CPU this only
validates the *math*: the derivatives reproduce ``derivative_bundle`` exactly (same
operator) and the fused RHS matches the verbatim RHS to round-off. The SMEM/halo
realization — the actual occupancy payoff and the Triton-0.9.2 halo-crop work — is
**H200-gated** (Phase 2 / 3.2d): here the kernel runs as one whole-grid program and
the on-chip derivatives use ``jnp.pad``/static slices (the shared ``SpatialDerivative``),
which interpret mode evaluates but Triton would not lower without the SMEM rewrite.

Run:  ``python -m bssn3d.fused_backend``  (regenerates ``_bssn_rhs_fused.py``).
"""

from __future__ import annotations

import hashlib
from datetime import date
from pathlib import Path

from ._codegen import DENDRO_CSE, FIELD_INPUTS, RHS_TO_FIELD
from ._bssn_rhs_generated import GRAD1_INPUTS, GRAD2_INPUTS
from .staging import build_dag, select_schedule, schedule_pylines
from .pallas_backend import DEFAULT_BUDGET

FUSED_OUT = Path(__file__).resolve().parent / "_bssn_rhs_fused.py"

OUTPUT_TOKENS = list(RHS_TO_FIELD)
OUTPUT_FIELDS = [RHS_TO_FIELD[t] for t in OUTPUT_TOKENS]

# Scalars the kernel unpacks (algebra params + the three grid spacings the on-chip
# derivatives need). dx_i (the CAHD dx^2/dt factor) is the x-spacing, so it reuses dx.
SCAL_SINGLE = ["eta", "BSSN_CAHD_C", "dt", "h_ssl", "sig_ssl", "t", "dx", "dy", "dz"]
# then lmbda[0..3], lambda_f[0..1]


def _stencil_tables() -> tuple[dict, dict]:
    """``{order: (coeff, ...)}`` for the 1st/2nd centred stencils, as plain Python
    floats. Read from the shared ``SpatialDerivative`` so they can never drift — but
    materialised as constants (not jnp arrays), since a ``pallas_call`` kernel may not
    capture jax arrays from its closure (it would, with ``_DIFF.compute_d1``)."""
    import jax
    jax.config.update("jax_enable_x64", True)   # else the stencils are float32-rounded
    from mcs_common.derivatives import SpatialDerivative
    import numpy as np
    c1, c2 = {}, {}
    for o in (4, 6, 8):
        d = SpatialDerivative(order=o)
        c1[o] = tuple(float(x) for x in np.asarray(d.C1))
        c2[o] = tuple(float(x) for x in np.asarray(d.C2))
    return c1, c2


def _deriv_lines() -> list[str]:
    """Field-streamed on-chip derivative assignments (binding the exact ``grad_*`` /
    ``grad2_*`` names the algebra references), via the local ``_d1``/``_d2`` helpers.
    Mirrors ``derivative_bundle`` op-for-op (same coeffs, same pad/slice/sum order) so
    the fused derivatives are bit-identical to the unfused FD path."""
    d_axis = {0: "dx", 1: "dy", 2: "dz"}
    grad1_by_field: dict[str, list[tuple[int, str]]] = {}
    for a, f in GRAD1_INPUTS:
        grad1_by_field.setdefault(f, []).append((a, f))
    grad2_by_field: dict[str, list[tuple[int, int, str]]] = {}
    for i, j, f in GRAD2_INPUTS:
        grad2_by_field.setdefault(f, []).append((i, j, f))

    lines: list[str] = []
    for f in FIELD_INPUTS:                       # stream one field at a time
        for a, _ in grad1_by_field.get(f, []):
            lines.append(f"grad_{a}_{f} = _d1({f}, {d_axis[a]}, {a})")
        for i, j, _ in grad2_by_field.get(f, []):
            if i == j:
                lines.append(f"grad2_{i}_{j}_{f} = _d2({f}, {d_axis[i]}, {i})")
            else:                                # mixed: compose d1 along i then j
                lines.append(
                    f"grad2_{i}_{j}_{f} = _d1(_d1({f}, {d_axis[i]}, {i}), "
                    f"{d_axis[j]}, {j})")
    return lines


def generate_fused(budget: int = DEFAULT_BUDGET, order: int = 6,
                   out: Path = FUSED_OUT) -> Path:
    dag = build_dag()
    sched = select_schedule(dag, budget=budget)
    algebra = schedule_pylines(dag, sched.materialize)   # M stored / R inlined
    derivs = _deriv_lines()
    c1_tbl, c2_tbl = _stencil_tables()
    src_hash = hashlib.sha256(DENDRO_CSE.read_bytes()).hexdigest()[:16]

    L: list[str] = []
    w = L.append
    w('"""AUTO-GENERATED by bssn3d.fused_backend — DO NOT EDIT BY HAND.')
    w("")
    w("Derivative-fused register-resident BSSN Pallas kernel (Step 3.2 / 1.2). One")
    w("pallas_call: the 24 fields in, the 138 derivatives computed ON-CHIP (never")
    w("materialized to HBM), the 3.2b scheduled algebra, the 24 RHS out. CPU interpret")
    w("mode validates the MATH (derivs == derivative_bundle, RHS == verbatim to")
    w("round-off); the SMEM/occupancy payoff + Triton halo-crop are H200-gated (3.2d).")
    w("")
    w(f"Transliterated from Dendro-GR  {DENDRO_CSE.name}  sha256[:16] = {src_hash}")
    w(f"  generated = {date.today().isoformat()}  |  FD order = {order}  |  "
      f"budget = {budget} regs")
    w(f"  materialized = {len(sched.materialize)}   peak_live = {sched.peak_live}   "
      f"recompute = {sched.multiplier:.2f}x")
    w("")
    w("Regenerate:  python -m bssn3d.fused_backend")
    w('"""')
    w("")
    w("import os")
    w("import jax")
    w("import jax.numpy as jnp")
    w("from jax import lax")
    w("from jax.experimental import pallas as pl")
    w("")
    w("# Force the Triton backend (Mosaic GPU isn't installed); same guard as the")
    w("# algebra-only kernel. Override with JAX_PALLAS_USE_MOSAIC_GPU=1.")
    w('if not os.environ.get("JAX_PALLAS_USE_MOSAIC_GPU"):')
    w('    jax.config.update("jax_pallas_use_mosaic_gpu", False)')
    w("")
    w(f"FIELD_INPUTS = {FIELD_INPUTS!r}")
    w(f"OUTPUT_FIELDS = {OUTPUT_FIELDS!r}")
    w(f"ORDER = int(os.environ.get('BSSN_FD_ORDER', '{order}'))")
    w("# Centred FD coefficients, copied from the shared SpatialDerivative (plain")
    w("# floats: a pallas_call kernel may not capture jax arrays from its closure).")
    w(f"_C1_TBL = {c1_tbl!r}")
    w(f"_C2_TBL = {c2_tbl!r}")
    w("_C1 = _C1_TBL[ORDER]")
    w("_C2 = _C2_TBL[ORDER]")
    w("_NG = ORDER // 2")
    w("PDTYPE = jnp.float32 if os.environ.get('BSSN_PALLAS_FP32') else jnp.float64")
    w('_INTERPRET = jax.default_backend() == "cpu"')
    w(f"NF = {len(FIELD_INPUTS)}")
    w(f"NOUT = {len(OUTPUT_TOKENS)}")
    w(f"NSCAL = {len(SCAL_SINGLE) + 6}")
    w("")
    w("")
    w("def _stencil(field, coeffs, factor, axis):")
    w("    # Static pad+slice centred difference — bit-identical to SpatialDerivative")
    w("    # ._apply (same coeffs, same edge pad, same left-to-right sum). On GPU this")
    w("    # jnp.pad/slice does NOT lower under Triton; the 2.5D-SMEM halo rewrite")
    w("    # (3.2d) is the H200 build. Interpret mode evaluates it directly.")
    w("    pad = [(_NG, _NG) if i == axis else (0, 0) for i in range(field.ndim)]")
    w("    p = jnp.pad(field, pad, mode='edge')")
    w("    n = field.shape[axis]")
    w("    return sum((coeffs[k] * factor) * lax.slice_in_dim(p, k, k + n, axis=axis)")
    w("               for k in range(len(coeffs)))")
    w("")
    w("")
    w("def _d1(field, dx, axis):")
    w("    return _stencil(field, _C1, 1.0 / dx, axis)")
    w("")
    w("")
    w("def _d2(field, dx, axis):")
    w("    return _stencil(field, _C2, 1.0 / (dx ** 2), axis)")
    w("")
    w("")
    w("def _kernel(feat_ref, scal_ref, out_ref):")
    w("    # Whole-grid program: feat_ref (NF, *shape) fields, out_ref (NOUT, *shape).")
    for k, name in enumerate(FIELD_INPUTS):
        w(f"    {name} = feat_ref[{k}]")
    for k, name in enumerate(SCAL_SINGLE):
        w(f"    {name} = scal_ref[{k}]")
    w("    dx_i = dx")                            # CAHD dx^2/dt factor uses x-spacing
    base = len(SCAL_SINGLE)
    w(f"    lmbda = [scal_ref[{base}], scal_ref[{base+1}], "
      f"scal_ref[{base+2}], scal_ref[{base+3}]]")
    w(f"    lambda_f = [scal_ref[{base+4}], scal_ref[{base+5}]]")
    w("")
    w("    # --- on-chip derivatives (field-streamed; never materialized to HBM) ---")
    for ln in derivs:
        w(f"    {ln}")
    w("")
    w("    # --- scheduled pointwise algebra (M-temps stored, R-temps inlined) ---")
    for ln in algebra:
        w(f"    {ln}")
    w("")
    for i, tok in enumerate(OUTPUT_TOKENS):
        w(f"    out_ref[{i}] = {tok}")
    w("")
    w("")
    w("def bssn_rhs_fused(F, dx, dy, dz, eta, lmbda, lambda_f, "
      "BSSN_CAHD_C, dt, h_ssl, sig_ssl, t):")
    w('    """Fused BSSN RHS: fields in (dict, full padded shape), {field: d/dt} out.')
    w("")
    w("    Derivatives are computed inside the kernel, so — unlike the algebra-only")
    w("    schemes — no derivative_bundle is built or passed. ``dx/dy/dz`` are the grid")
    w('    spacings; the remaining args match the algebra params."""')
    w("    shape = F['alpha'].shape")
    w("    feat = jnp.stack([F[n] for n in FIELD_INPUTS]).astype(PDTYPE)")
    w("    scal = jnp.asarray([eta, BSSN_CAHD_C, dt, h_ssl, sig_ssl, t, dx, dy, dz,")
    w("                        lmbda[0], lmbda[1], lmbda[2], lmbda[3],")
    w("                        lambda_f[0], lambda_f[1]], dtype=PDTYPE)")
    w("    out = pl.pallas_call(")
    w("        _kernel,")
    w("        grid=(1,),")
    w("        in_specs=[pl.BlockSpec((NF,) + shape, lambda i: (0,) + (0,) * len(shape)),")
    w("                  pl.BlockSpec((NSCAL,), lambda i: (0,))],")
    w("        out_specs=pl.BlockSpec((NOUT,) + shape, lambda i: (0,) + (0,) * len(shape)),")
    w("        out_shape=jax.ShapeDtypeStruct((NOUT,) + shape, PDTYPE),")
    w("        interpret=_INTERPRET,")
    w("    )(feat, scal)")
    w("    return {field: out[i].astype(jnp.float64)")
    w("            for i, field in enumerate(OUTPUT_FIELDS)}")

    out.write_text("\n".join(L) + "\n")
    return out


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(
        description="Emit the derivative-fused BSSN Pallas kernel.")
    ap.add_argument("--budget", type=int, default=DEFAULT_BUDGET)
    ap.add_argument("--order", type=int, default=6)
    a = ap.parse_args()
    p = generate_fused(budget=a.budget, order=a.order)
    print(f">> wrote {p}  | budget={a.budget}, FD order={a.order}")
