"""Phase 3.2c — emit the scheduled BSSN algebra as a register-resident Pallas kernel.

The 3.2b schedule (`staging.schedule_pylines`) partitions the CSE into a materialize
set M (stored) and a recompute set R (inlined per use). XLA could not realize the
recompute half (forward eval, no `remat`); Pallas can — we own the register file. The
algebra is **pointwise** (derivatives are inputs, the `_wo_derivs` design → no halo, no
stencil), so the kernel is embarrassingly parallel over grid points: stack the 24 fields
+ 138 derivatives into one ``(NIN=162, Npts)`` array, tile along points, and each block
runs the scheduled straight-line algebra with M-temps as register scalars and R-temps
recomputed inline.

This emits ``_bssn_rhs_pallas.py`` (committed, reviewable) with a signature-compatible
``bssn_rhs_algebra`` so it drops into ``BSSNSolver(scheme="pallas")`` and reuses the
oracle/apples harness. Local runs use Pallas ``interpret=True`` (CPU math only — does
NOT test compilation/registers); the spill/regime check is a Marylou run (3.2c gate).

Run:  ``python -m bssn3d.pallas_backend``  (regenerates ``_bssn_rhs_pallas.py``).
"""

from __future__ import annotations

import hashlib
from datetime import date
from pathlib import Path

from ._codegen import DENDRO_CSE, FIELD_INPUTS, RHS_TO_FIELD
from ._bssn_rhs_generated import GRAD1_INPUTS, GRAD2_INPUTS
from .staging import build_dag, select_schedule, schedule_pylines

PALLAS_OUT = Path(__file__).resolve().parent / "_bssn_rhs_pallas.py"

GRAD1_NAMES = [f"grad_{a}_{f}" for a, f in GRAD1_INPUTS]
GRAD2_NAMES = [f"grad2_{i}_{j}_{f}" for i, j, f in GRAD2_INPUTS]
DERIV_NAMES = GRAD1_NAMES + GRAD2_NAMES
INPUT_NAMES = FIELD_INPUTS + DERIV_NAMES          # feat rows, in order
OUTPUT_TOKENS = list(RHS_TO_FIELD)                # a_rhs, chi_rhs, ... (store order)
OUTPUT_FIELDS = [RHS_TO_FIELD[t] for t in OUTPUT_TOKENS]

# Packed scalar order (kernel unpacks in this order; wrapper packs identically).
SCAL_SINGLE = ["eta", "BSSN_CAHD_C", "dt", "dx_i", "h_ssl", "sig_ssl", "t"]
# then lmbda[0..3], lambda_f[0..1]

DEFAULT_BUDGET = 200


def generate_pallas(budget: int = DEFAULT_BUDGET, out: Path = PALLAS_OUT) -> Path:
    dag = build_dag()
    sched = select_schedule(dag, budget=budget)
    lines = schedule_pylines(dag, sched.materialize)   # M-temp + output assignments
    src_hash = hashlib.sha256(DENDRO_CSE.read_bytes()).hexdigest()[:16]

    L: list[str] = []
    w = L.append
    w('"""AUTO-GENERATED by bssn3d.pallas_backend — DO NOT EDIT BY HAND.')
    w("")
    w("Register-resident Pallas BSSN algebra (Step 3.2c). Pointwise kernel over grid")
    w("points; the 3.2b materialize/recompute schedule is realized as straight-line")
    w("code (M-temps stored, R-temps inlined). Same algebra as the verbatim module.")
    w("")
    w(f"Transliterated from Dendro-GR  {DENDRO_CSE.name}  sha256[:16] = {src_hash}")
    w(f"  generated = {date.today().isoformat()}  |  budget = {budget} regs")
    w(f"  materialized = {len(sched.materialize)}   peak_live = {sched.peak_live}   "
      f"recompute = {sched.multiplier:.2f}x")
    w("")
    w("Regenerate:  python -m bssn3d.pallas_backend")
    w('"""')
    w("")
    w("import os")
    w("from math import prod")
    w("import jax")
    w("import jax.numpy as jnp")
    w("from jax.experimental import pallas as pl")
    w("from jax.experimental.pallas import triton as plgpu")
    w("")
    w("# JAX 0.10 defaults `jax_pallas_use_mosaic_gpu = True`; Mosaic GPU isn't")
    w("# installed, so pallas_call falls through with a misleading 'install jaxlib")
    w("# GPU' error instead of using Triton (which IS available). Force Triton —")
    w("# same guard as mcs2d/schemes/pallas_ozaki.py. Override with")
    w("# JAX_PALLAS_USE_MOSAIC_GPU=1 if Mosaic becomes available.")
    w('if not os.environ.get("JAX_PALLAS_USE_MOSAIC_GPU"):')
    w('    jax.config.update("jax_pallas_use_mosaic_gpu", False)')
    w("")
    w(f"FIELD_INPUTS = {FIELD_INPUTS!r}")
    w(f"INPUT_NAMES = {INPUT_NAMES!r}")
    w(f"OUTPUT_FIELDS = {OUTPUT_FIELDS!r}")
    w(f"NIN = {len(INPUT_NAMES)}")
    w(f"NOUT = {len(OUTPUT_TOKENS)}")
    w(f"NSCAL = {len(SCAL_SINGLE) + 6}")
    w("")
    w("# Block size along the (flattened) point axis. Pow2; override with BSSN_PALLAS_BS.")
    w('BS = int(os.environ.get("BSSN_PALLAS_BS", "256"))')
    w("# Triton occupancy lever (the real register knob, Step 3.2c): num_warps sets")
    w("# threads/block = 32*num_warps. With 1 point/thread (BS == 32*num_warps) a SMALL")
    w("# block lets ptxas use ~255 regs/thread instead of capping at 32 for occupancy.")
    w("# None → Triton auto. Override with BSSN_PALLAS_WARPS.")
    w('_NW = os.environ.get("BSSN_PALLAS_WARPS")')
    w("NUM_WARPS = int(_NW) if _NW else None")
    w("# Mixed-precision register-fit lever (Phase 3.2c): compute the algebra in fp32")
    w("# (the ~100-150-value Ricci working set is 2 regs/value in fp64 but 1 in fp32,")
    w("# so fp32 should fit the 255-reg file → spill collapse). FD stays fp64 upstream;")
    w("# inputs are cast here, output cast back to fp64. Toggle with BSSN_PALLAS_FP32=1.")
    w('PDTYPE = jnp.float32 if os.environ.get("BSSN_PALLAS_FP32") else jnp.float64')
    w('_INTERPRET = jax.default_backend() == "cpu"')
    w("")
    w("")
    w("def _kernel(feat_ref, scal_ref, out_ref):")
    w("    # Pointwise BSSN RHS over a BS-point block (feat_ref: (NIN, BS)).")
    # unpack inputs (feat rows) — bound once; loads rematerialise under the allocator
    for k, name in enumerate(INPUT_NAMES):
        w(f"    {name} = feat_ref[{k}]")
    # unpack scalars
    for k, name in enumerate(SCAL_SINGLE):
        w(f"    {name} = scal_ref[{k}]")
    base = len(SCAL_SINGLE)
    w(f"    lmbda = [scal_ref[{base}], scal_ref[{base+1}], "
      f"scal_ref[{base+2}], scal_ref[{base+3}]]")
    w(f"    lambda_f = [scal_ref[{base+4}], scal_ref[{base+5}]]")
    w("")
    # the scheduled algebra body (M-temps stored, R inlined, then the 24 outputs)
    for ln in lines:
        w(f"    {ln}")
    w("")
    # store outputs in OUTPUT_TOKENS order
    for i, tok in enumerate(OUTPUT_TOKENS):
        w(f"    out_ref[{i}] = {tok}")
    w("")
    w("")
    w("def bssn_rhs_algebra(F, D, eta, lmbda, lambda_f, "
      "BSSN_CAHD_C, dt, dx_i, h_ssl, sig_ssl, t):")
    w('    """Pallas BSSN RHS algebra (signature-compatible with the verbatim module)."""')
    w('    shape = F["alpha"].shape')
    w("    npts = prod(shape)")
    w("    feat = jnp.stack([F[n].reshape(-1) for n in FIELD_INPUTS]")
    w("                     + [D[n].reshape(-1) for n in INPUT_NAMES[len(FIELD_INPUTS):]]")
    w("                     ).astype(PDTYPE)")
    w("    scal = jnp.asarray([eta, BSSN_CAHD_C, dt, dx_i, h_ssl, sig_ssl, t,")
    w("                        lmbda[0], lmbda[1], lmbda[2], lmbda[3],")
    w("                        lambda_f[0], lambda_f[1]], dtype=PDTYPE)")
    w("    npad = ((npts + BS - 1) // BS) * BS")
    w("    if npad != npts:")
    w("        feat = jnp.pad(feat, ((0, 0), (0, npad - npts)), mode='edge')")
    w("    nblk = npad // BS")
    w("    cparams = (plgpu.CompilerParams(num_warps=NUM_WARPS)")
    w("               if NUM_WARPS is not None else None)")
    w("    out = pl.pallas_call(")
    w("        _kernel,")
    w("        grid=(nblk,),")
    w("        in_specs=[pl.BlockSpec((NIN, BS), lambda i: (0, i)),")
    w("                  pl.BlockSpec((NSCAL,), lambda i: (0,))],")
    w("        out_specs=pl.BlockSpec((NOUT, BS), lambda i: (0, i)),")
    w("        out_shape=jax.ShapeDtypeStruct((NOUT, npad), PDTYPE),")
    w("        interpret=_INTERPRET,")
    w("        compiler_params=cparams,")
    w("    )(feat, scal)")
    w("    return {field: out[i, :npts].astype(jnp.float64).reshape(shape)")
    w("            for i, field in enumerate(OUTPUT_FIELDS)}")

    out.write_text("\n".join(L) + "\n")
    return out


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(
        description="Emit the register-resident BSSN Pallas kernel at a given budget.")
    ap.add_argument("--budget", type=int, default=DEFAULT_BUDGET,
                    help="target persistent-liveness budget for the materialize set. "
                         "Large (e.g. 100000) → materialize everything (no recompute; "
                         "let ptxas remat). Small → more recompute, fewer stored temps.")
    a = ap.parse_args()
    from .staging import build_dag, select_schedule
    sched = select_schedule(build_dag(), budget=a.budget)
    p = generate_pallas(budget=a.budget)
    print(f">> wrote {p}  | budget={a.budget} → |M|={len(sched.materialize)}, "
          f"peak_live={sched.peak_live}, recompute={sched.multiplier:.2f}x")
