// M2a — device derivative stage (correctness baseline) for Step 3.2e.
//
// Computes all 138 grad_/grad2_ derivatives the BSSN algebra consumes, 1 thread per grid point,
// reading neighbours from global memory with edge-CLAMP (= the mode='edge' pad derivative_bundle
// uses). Validates the device derivative MATH + that the FFI carries the real 24-field-in /
// 138-deriv-out workload, against derivative_bundle / the M0 CPU reference (to fp64 round-off; the
// kernel may FMA-contract, so the bar is ~1e-12, not bit-exact). The SMEM 2.5D streaming geometry
// (wall A) is M2b, layered on this proven math.
//
// Spec (which deriv = which field/kind/axes, + the 6th-order stencils) is in _deriv_kernel.cuh,
// generated by gen_deriv_kernel.py. Mixed grad2_ij is the nested d1_i-then-d1_j grouping, matching
// derivative_bundle's two-step compose.
//
// Build: build_deriv.sh  (sm_90a H100/H200; sm_80 A100; sm_100a B200).

#include <cstdint>
#include <string>

#include <cuda_runtime.h>

#include "xla/ffi/api/ffi.h"
#include "_deriv_kernel.cuh"

namespace ffi = xla::ffi;

__device__ __forceinline__ int clampi(int v, int hi) {
  return v < 0 ? 0 : (v > hi ? hi : v);
}

__global__ void deriv_kernel(const double* __restrict__ fields,
                             double* __restrict__ out,
                             int Sx, int Sy, int Sz, std::int64_t N,
                             double dx, double dy, double dz) {
  const std::int64_t p = static_cast<std::int64_t>(blockIdx.x) * blockDim.x + threadIdx.x;
  if (p >= N) return;

  // decode (x,y,z) from the C-order flat index p = (x*Sy + y)*Sz + z
  const int z = static_cast<int>(p % Sz);
  const std::int64_t t = p / Sz;
  const int y = static_cast<int>(t % Sy);
  const int x = static_cast<int>(t / Sy);

  const int coord[3] = {x, y, z};
  const int hi[3] = {Sx - 1, Sy - 1, Sz - 1};
  const std::int64_t stride[3] = {static_cast<std::int64_t>(Sy) * Sz, Sz, 1};
  const double invh[3] = {1.0 / dx, 1.0 / dy, 1.0 / dz};
  const int R = FD_REACH;

  for (int d = 0; d < N_DERIV; ++d) {
    const double* __restrict__ F = fields + static_cast<std::int64_t>(D_FIELD[d]) * N;
    const int i = D_AXI[d];
    double val;

    if (D_KIND[d] != KIND_GRAD2_MIXED) {                 // grad1 or diagonal grad2
      const double* C = (D_KIND[d] == KIND_GRAD1) ? DC1 : DC2;
      const double fac = (D_KIND[d] == KIND_GRAD1) ? invh[i] : invh[i] * invh[i];
      double acc = 0.0;
      for (int a = 0; a < 2 * R + 1; ++a) {
        const int ci = clampi(coord[i] + (a - R), hi[i]);
        acc += C[a] * F[p + static_cast<std::int64_t>(ci - coord[i]) * stride[i]];
      }
      val = acc * fac;
    } else {                                             // mixed: d1_i then d1_j (nested)
      const int j = D_AXJ[d];
      double acc = 0.0;
      for (int b = 0; b < 2 * R + 1; ++b) {
        const int cj = clampi(coord[j] + (b - R), hi[j]);
        const std::int64_t off_j = static_cast<std::int64_t>(cj - coord[j]) * stride[j];
        double inner = 0.0;
        for (int a = 0; a < 2 * R + 1; ++a) {
          const int ci = clampi(coord[i] + (a - R), hi[i]);
          inner += DC1[a] * F[p + static_cast<std::int64_t>(ci - coord[i]) * stride[i] + off_j];
        }
        acc += DC1[b] * inner;
      }
      val = acc * invh[i] * invh[j];
    }
    out[static_cast<std::int64_t>(d) * N + p] = val;
  }
}

static ffi::Error DerivImpl(cudaStream_t stream,
                            ffi::Buffer<ffi::F64> fields,    // (N_FIELDS, Sx, Sy, Sz)
                            ffi::ResultBuffer<ffi::F64> out, // (N_DERIV, Sx, Sy, Sz)
                            double dx, double dy, double dz) {
  const auto dims = fields.dimensions();
  if (dims.size() != 4) return ffi::Error::Internal("deriv: fields must be 4-D (NF,Sx,Sy,Sz)");
  if (dims[0] != N_FIELDS) return ffi::Error::Internal("deriv: fields[0] != N_FIELDS");
  const int Sx = static_cast<int>(dims[1]);
  const int Sy = static_cast<int>(dims[2]);
  const int Sz = static_cast<int>(dims[3]);
  const std::int64_t N = static_cast<std::int64_t>(Sx) * Sy * Sz;

  const int block = 128;
  const std::int64_t grid = (N + block - 1) / block;
  deriv_kernel<<<grid, block, 0, stream>>>(fields.typed_data(), out->typed_data(),
                                           Sx, Sy, Sz, N, dx, dy, dz);
  const cudaError_t err = cudaGetLastError();
  if (err != cudaSuccess) {
    return ffi::Error::Internal(std::string("deriv launch failed: ") + cudaGetErrorString(err));
  }
  return ffi::Error::Success();
}

XLA_FFI_DEFINE_HANDLER_SYMBOL(
    Deriv, DerivImpl,
    ffi::Ffi::Bind()
        .Ctx<ffi::PlatformStream<cudaStream_t>>()
        .Arg<ffi::Buffer<ffi::F64>>()      // fields
        .Ret<ffi::Buffer<ffi::F64>>()      // out
        .Attr<double>("dx")
        .Attr<double>("dy")
        .Attr<double>("dz"));
