"""Generate the FULL BSSN algebra as a naive CUDA kernel — the right-SCALE wall-B test.

The Step 3.2f microbenches (christoffel, ricci) were too small: a single tensor's working
set fits the register file, so they could only measure warp-coop OVERHEAD, never the
register-fit benefit (which only appears once the co-resident working set overflows). The
real wall-B pressure is the WHOLE algebra held live at once — the 138 derivatives + the
~826 CSE temps that all feed the 24 outputs. So we transliterate the actual generated CSE
(`bssneqs_SSL_HD_dxsq.cpp`, the production CAHD+SSL variant) into a naive 1-thread-per-point
CUDA kernel and measure: does it spill in nvcc/ptxas (as it did in Triton/Pallas), and in
which regime (register spill vs local-memory arrays)? This is the baseline a warp-coop (or
any wall-B) kernel must beat.

The transliteration is trivial (the JAX one already showed the body is pure arithmetic):
C math names (pow/sqrt/exp) are already valid; the only change is the C++ keyword `lambda`
-> `lmbda`. Each `DENDRO_N = <expr>` becomes `double DENDRO_N = <expr>;`, the 24 outputs
write to global. Field/deriv/scalar inputs are read once per point (SoA, coalesced).

Test vectors are validated against the JAX verbatim algebra (the bit-checked oracle): same
expression, same order, so they agree to fp64 round-off.

Run:  `python -m bssn3d.cuda.gen_algebra_cuda`
  -> writes  _bssn_algebra_kernel.cuh  (the generated kernel)
     and     algebra_vectors.bin       (oracle-validated inputs + expected outputs)
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from jax import config as _jax_config
_jax_config.update("jax_enable_x64", True)
import jax.numpy as jnp

from bssn3d._codegen import (
    parse, _LAMBDA_RE, FIELD_INPUTS, RHS_TO_FIELD, DENDRO_CSE,
)
from bssn3d._bssn_rhs_generated import bssn_rhs_algebra
from bssn3d.state import PhysicsParams

HERE = Path(__file__).resolve().parent
CUH = HERE / "_bssn_algebra_kernel.cuh"
VEC = HERE / "algebra_vectors.bin"

# scalar pack order shared by the kernel (S[0..12]) and the vector writer
_SCALAR_ORDER = ["eta", "BSSN_CAHD_C", "dt", "dx_i", "h_ssl", "sig_ssl", "t",
                 "lmbda0", "lmbda1", "lmbda2", "lmbda3", "lambda_f0", "lambda_f1"]


def _deriv_names(grad1, grad2):
    return ([f"grad_{a}_{f}" for a, f in grad1]
            + [f"grad2_{i}_{j}_{f}" for i, j, f in grad2])


def emit_kernel(statements, grad1, grad2) -> str:
    deriv = _deriv_names(grad1, grad2)
    L, w = [], lambda s: L.append(s)
    w("// AUTO-GENERATED by bssn3d.cuda.gen_algebra_cuda — DO NOT EDIT BY HAND.")
    w(f"// transliterated from {DENDRO_CSE.name}: {len(statements)} statements, "
      f"{len(deriv)} derivs, {len(RHS_TO_FIELD)} outputs.")
    w("#pragma once")
    w(f"#define NF {len(FIELD_INPUTS)}")
    w(f"#define ND {len(deriv)}")
    w(f"#define NOUT {len(RHS_TO_FIELD)}")
    w(f"#define NSCAL {len(_SCALAR_ORDER)}")
    w("")
    w("// 1 thread / point. Reads 24 fields + 138 derivs (SoA, coalesced) into local")
    w("// scalars, runs the full CSE algebra, writes 24 outputs. Expected to push ptxas")
    w("// hard (peak ~452 simultaneously-live fp64 temps) -> the wall-B baseline.")
    w("__global__ void bssn_algebra(const double* __restrict__ F,")
    w("                             const double* __restrict__ D,")
    w("                             const double* __restrict__ S,")
    w("                             double* __restrict__ OUT, int npts) {")
    w("  int p = blockIdx.x * blockDim.x + threadIdx.x;")
    w("  if (p >= npts) return;")
    w("  size_t P = (size_t)npts;")
    w("  double eta=S[0], BSSN_CAHD_C=S[1], dt=S[2], dx_i=S[3], h_ssl=S[4],")
    w("         sig_ssl=S[5], t=S[6];")
    w("  double lmbda[4]={S[7],S[8],S[9],S[10]};")
    w("  double lambda_f[2]={S[11],S[12]};")
    for k, name in enumerate(FIELD_INPUTS):
        w(f"  double {name}=F[{k}*P+p];")
    for k, name in enumerate(deriv):
        w(f"  double {name}=D[{k}*P+p];")
    declared = set(FIELD_INPUTS) | set(deriv)
    for lhs, rhs in statements:
        crhs = _LAMBDA_RE.sub("lmbda", rhs)
        if lhs in declared:
            w(f"  {lhs}={crhs};")
        else:
            w(f"  double {lhs}={crhs};")
            declared.add(lhs)
    for k, tok in enumerate(RHS_TO_FIELD):
        w(f"  OUT[{k}*P+p]={tok};")
    w("}")
    return "\n".join(L) + "\n"


def _make_inputs(npts, rng):
    """Near-Minkowski fields + small derivatives (keeps chi>0, det(g~)>0, alpha>0 so
    the algebra is finite). Correctness is invariant to the inputs — both sides
    evaluate the same function — but finiteness needs a physical-ish neighbourhood."""
    f = {}
    diag = {"alpha", "chi", "gt0", "gt3", "gt5"}
    for name in FIELD_INPUTS:
        base = 1.0 if name in diag else 0.0
        f[name] = base + 0.03 * rng.standard_normal(npts)
    return f


def write_vectors(statements, grad1, grad2, npts=1 << 18, seed=1):
    deriv = _deriv_names(grad1, grad2)
    rng = np.random.default_rng(seed)
    pp = PhysicsParams()
    F = _make_inputs(npts, rng)
    D = {name: 0.03 * rng.standard_normal(npts) for name in deriv}
    scal = {"eta": pp.eta, "BSSN_CAHD_C": pp.cahd_c, "dt": 0.01, "dx_i": 0.1,
            "h_ssl": pp.ssl_h, "sig_ssl": pp.ssl_sigma, "t": 0.0,
            "lmbda0": pp.lmbda[0], "lmbda1": pp.lmbda[1], "lmbda2": pp.lmbda[2],
            "lmbda3": pp.lmbda[3], "lambda_f0": pp.lambda_f[0], "lambda_f1": pp.lambda_f[1]}

    # JAX oracle (the bit-validated verbatim algebra)
    Fj = {k: jnp.asarray(v) for k, v in F.items()}
    Dj = {k: jnp.asarray(v) for k, v in D.items()}
    out = bssn_rhs_algebra(Fj, Dj, pp.eta, pp.lmbda, pp.lambda_f,
                           pp.cahd_c, scal["dt"], scal["dx_i"],
                           pp.ssl_h, pp.ssl_sigma, scal["t"])
    expected = np.stack([np.asarray(out[field]) for field in RHS_TO_FIELD.values()])

    Fm = np.stack([F[n] for n in FIELD_INPUTS])             # (NF, npts)
    Dm = np.stack([D[n] for n in deriv])                    # (ND, npts)
    Sm = np.array([scal[k] for k in _SCALAR_ORDER])         # (NSCAL,)
    with open(VEC, "wb") as fh:
        np.array([npts], dtype=np.int64).tofile(fh)
        Sm.astype(np.float64).tofile(fh)
        Fm.astype(np.float64).tofile(fh)
        Dm.astype(np.float64).tofile(fh)
        expected.astype(np.float64).tofile(fh)
    return expected.shape


def main():
    statements, grad1, grad2 = parse(DENDRO_CSE)
    CUH.write_text(emit_kernel(statements, grad1, grad2))
    print(f">> wrote {CUH.name}: {len(statements)} statements, "
          f"{len(_deriv_names(grad1, grad2))} derivs, {len(RHS_TO_FIELD)} outputs")
    shape = write_vectors(statements, grad1, grad2)
    sz = VEC.stat().st_size / 1e6
    print(f">> wrote {VEC.name}: outputs {shape}, {sz:.1f} MB "
          f"(npts + {len(_SCALAR_ORDER)} scalars + NF + ND + NOUT, float64)")


if __name__ == "__main__":
    main()
