"""Generate `_deriv_kernel.cuh` — the spec tables for the M2a device derivative kernel.

M2a is the **correctness baseline** for Step 3.2e's derivative stage: a data-driven CUDA kernel
that computes all 138 `grad_/grad2_` derivatives the BSSN algebra consumes (1 thread/point, reads
neighbours from global memory with edge-clamp = the `mode='edge'` pad `derivative_bundle` uses).
It validates the device derivative MATH + that the FFI carries the real 24-field-in / 138-deriv-out
workload, against `derivative_bundle` (= the M0 reference, bit-identical). The SMEM 2.5D streaming
(the wall-A geometry) is M2b, layered on this proven math.

This emits the **fixed** spec the kernel loops over (from `GRAD1_INPUTS` / `GRAD2_INPUTS`):
  * the 6th-order stencils C1 (1st deriv) and C2 (2nd diagonal), reach 3;
  * per-derivative tables D_FIELD / D_KIND / D_AXI / D_AXJ (kind: 0=grad1, 1=grad2-diag, 2=mixed).
The deriv ORDER is grad1 (GRAD1_INPUTS order) then grad2 (GRAD2_INPUTS order) — `deriv_kernel.py`
maps the kernel's `out[d]` back to names with the SAME order.

Run:  `python -m bssn3d.cuda.gen_deriv_kernel`  ->  writes  _deriv_kernel.cuh
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from bssn3d._bssn_rhs_generated import FIELD_INPUTS, GRAD1_INPUTS, GRAD2_INPUTS
from mcs_common.derivatives import SpatialDerivative

OUT = Path(__file__).resolve().parent / "_deriv_kernel.cuh"

# Canonical deriv order shared with deriv_kernel.py: grad1 then grad2, input order.
KIND_GRAD1, KIND_GRAD2_DIAG, KIND_GRAD2_MIXED = 0, 1, 2


def deriv_order():
    """The 138 (name, field, kind, i, j) specs in kernel/output order."""
    fidx = {f: k for k, f in enumerate(FIELD_INPUTS)}
    specs = []
    for axis, f in GRAD1_INPUTS:
        specs.append((f"grad_{axis}_{f}", fidx[f], KIND_GRAD1, axis, axis))
    for i, j, f in GRAD2_INPUTS:
        kind = KIND_GRAD2_DIAG if i == j else KIND_GRAD2_MIXED
        specs.append((f"grad2_{i}_{j}_{f}", fidx[f], kind, i, j))
    return specs


def deriv_csr():
    """Per-field CSR grouping (for the SMEM streaming kernel, which processes one field at a
    time). Returns (fstart[N_FIELDS+1], out_idx[138], kind[138], axi[138], axj[138]) where for
    field f the derivs are entries fstart[f]..fstart[f+1], and out_idx gives the output slot
    (the d index in deriv_order, so writes stay aligned with the flat layout / M2a)."""
    specs = deriv_order()
    by_field = {}
    for d, (_, fidx, kind, i, j) in enumerate(specs):
        by_field.setdefault(fidx, []).append((d, kind, i, j))
    fstart, out_idx, kind, axi, axj = [0], [], [], [], []
    for f in range(len(FIELD_INPUTS)):
        for (d, k, i, j) in by_field.get(f, []):
            out_idx.append(d); kind.append(k); axi.append(i); axj.append(j)
        fstart.append(len(out_idx))
    return fstart, out_idx, kind, axi, axj


def _carr(name, vals, ctype="int"):
    body = ", ".join(repr(v) if ctype == "int" else v for v in vals)
    return f"__constant__ {ctype} {name}[{len(vals)}] = {{{body}}};"


def generate(out: Path = OUT) -> Path:
    diff = SpatialDerivative(order=6)
    C1 = np.asarray(diff.C1, dtype=np.float64)
    C2 = np.asarray(diff.C2, dtype=np.float64)
    reach = (C1.shape[0] - 1) // 2
    assert reach == (C2.shape[0] - 1) // 2 == 3

    specs = deriv_order()
    # emit stencil coeffs as exact integer/denominator fp64 (matches numpy's array/denom)
    c1_terms = ["(%d.0/60.0)" % round(v * 60) for v in C1]
    c2_terms = ["(%d.0/180.0)" % round(v * 180) for v in C2]

    lines = [
        "// AUTO-GENERATED by gen_deriv_kernel.py — do not edit. (M2a derivative spec)",
        "#pragma once",
        f"#define N_FIELDS {len(FIELD_INPUTS)}",
        f"#define N_DERIV  {len(specs)}",
        f"#define FD_REACH {reach}",
        "#define KIND_GRAD1 0",
        "#define KIND_GRAD2_DIAG 1",
        "#define KIND_GRAD2_MIXED 2",
        "",
        _carr("DC1", c1_terms, "double"),
        _carr("DC2", c2_terms, "double"),
        _carr("D_FIELD", [s[1] for s in specs]),
        _carr("D_KIND", [s[2] for s in specs]),
        _carr("D_AXI", [s[3] for s in specs]),
        _carr("D_AXJ", [s[4] for s in specs]),
        "",
        "// per-field CSR (SMEM streaming kernel: derivs of field f = entries D_FSTART[f]..[f+1])",
    ]
    fstart, out_idx, kind_s, axi_s, axj_s = deriv_csr()
    lines += [
        _carr("D_FSTART", fstart),
        _carr("D_OUTIDX", out_idx),
        _carr("D_KIND_S", kind_s),
        _carr("D_AXI_S", axi_s),
        _carr("D_AXJ_S", axj_s),
        "",
    ]
    out.write_text("\n".join(lines))
    print(f">> wrote {out.name}: {len(FIELD_INPUTS)} fields, {len(specs)} derivs "
          f"({sum(s[2]==KIND_GRAD1 for s in specs)} grad1, "
          f"{sum(s[2]==KIND_GRAD2_DIAG for s in specs)} diag, "
          f"{sum(s[2]==KIND_GRAD2_MIXED for s in specs)} mixed)")
    return out


if __name__ == "__main__":
    generate()
