xmin = -5.0
xmax = 5.0
ymin = -5.0
ymax = 5.0
zmin = -5.0
zmax = 5.0

cfl = 0.02 #0.02 3D, 0.05 2D
enable_cs = 1.0

bc_type = "periodic" #periodic, sommerfeld, directional
scheme = "floating_point" #floating_point, ozaki
id_type = "birefringent" #gaussian, birefringent
Nx = 256
Ny = 256
Nz = 64
Nt = 1500
Order = 8
output_interval = 10
sponge_strength = 0

ko_sigma = 0.05
Lambda = 2
id_amp = 0.8
id_sigma = 1
id_y0 = 0.0
id_x0 = 0.0
id_z0 = 0.0
K1 = 1
K2 = 1